spring:
  datasource:
    url: jdbc:h2:mem:aitravelplanner_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: WARN

app:
  security:
    jwt:
      secret: test-secret-key-change-me-0123456789
      issuer: ai-travel-planner-test
      access-token-ttl: PT15M
      refresh-token-ttl: PT1H
